### ISSUE TITLE
Complete v1 Hit List

### ISSUE THREAD

**Issue by skuhlmann** [yeet-haus/frames#2]
# 20240412 Hit List

Items needed to get this shipped.

## Done

- [x] new yeet  - low min
- [x] fetch and display dao data
- [x] pass data to tx frame (contract address, amount, message)
- [x] make tx work
- [x] error handling for bad yeeterid
- [x] error handling for not in yeet period
- [x] Add button linking to project on Yeeter
- [x] Add UI elements to home view
- [x] Add background image to `/success` view
- [x] Update `if (!yeetData.data.yeeter)` error
- [x] Update `!isActive` error (YEET Closed)
- [x] Update `if (!metaRes.data.records[0])` error
- [x] Style root view
- [x] Format Ends date like "Month day"
- [x] Add Neynar verification
- [x] Create `frames.yeet.haus` subdomain
- [x] Deploy to Vercel
- [x] Resolve "Yeeter Not Found" error
  - `yeetData.data.yeeter` is returning null

## Check

- Seems like the mission information is getting cached
- The amount raised is getting cached

## Backlog

- User inputs message
- User can YEET more than min
- Create NFT for Bottle of Bourbon campaign
- Add share button from project page
  - [Warpcast Cast Intents](https://docs.farcaster.xyz/reference/warpcast/cast-composer-intents)
- Write an article
- Add issues to board
- Submit for whitelist approval
- Add WTF view explaining what is going on
- Clear image cache
- Fix Neynar verification
- Add Airstack tracking
- Animate success `.gif`
- Investigate `3737ms` response time
- Add ability to select wallet from mobile :shrug:
- Test and determine how we want to handle `if (!metaRes.data.records[0])` error
- Update `if !isActive` error to have separate errors for "Coming Soon" or "YEET Ended"
  - If "YEET Ended" show either Success or Failure view
- Optimize code
  - Reduce redundancy of styles
  - Possibly break into multiple files

**Comment by earth2travis** [comment]
Need to know how to differentiate these two "INVALID YEETS"

## `yeetData.data.yeeter`

```json
{
  balance: '5000000000000000',
  dao: { id: '0x3b49c22b81a5153785ab4fc9c3eef126d3dc8199' },
  endTime: '1713549600',
  goal: '88800000000000000',
  id: '0x7a11f48c4231bd8cf1b4ee6084cdcd59c689cab1',
  minTribute: '1000000000000000',
  multiplier: '10000',
  startTime: '1712944800'
}
```

## `metaRes.data.records[0]`

```json
{
  id: '0x3b49c22b81a5153785ab4fc9c3eef126d3dc8199-record-1712948581177',
  content: '{"daoId":"0x3b49c22b81a5153785ab4fc9c3eef126d3dc8199","table":"yeetDetails","queryType":"latest","projectDetails":"","missionStatement":"Our mission is to collectively buy a Proud Peacher","icon":"","links":["{\\"url\\":\\"\\",\\"label\\":\\"Discord\\"}","{\\"url\\":\\"\\",\\"label\\":\\"Github\\"}","{\\"url\\":\\"\\",\\"label\\":\\"Blog\\"}","{\\"url\\":\\"\\",\\"label\\":\\"Telegram\\"}","{\\"url\\":\\"\\",\\"label\\":\\"Twitter\\"}","{\\"url\\":\\"\\",\\"label\\":\\"Web\\"}","{\\"url\\":\\"\\",\\"label\\":\\"\\"}","{\\"url\\":\\"\\",\\"label\\":\\"\\"}","{\\"url\\":\\"\\",\\"label\\":\\"\\"}"]}',
  dao: { name: 'Cop Some PEACHES' }
}
```

**Comment by earth2travis** [comment]
## Done

- [x] Add button linking to project on Yeeter
- [x] Add UI elements to home view
- [x] Add background image to `/success` view
- [x] Update `if (!yeetData.data.yeeter)` error
- [x] Update `!isActive` error (YEET Closed)
- [x] Update `if (!metaRes.data.records[0])` error
- [x] Style root view
- [x] Format Ends date like "Month day"
- [x] Add Neynar verification
- [x] Create `frames.yeet.haus` subdomain
- [x] Deploy to Vercel
- [x] Resolve "Yeeter Not Found" error
  - `yeetData.data.yeeter` is returning null

## Check

- Seems like the mission information is getting cached
- The amount raised is getting cached

## Backlog

- Create NFT for Bottle of Bourbon campaign
- Add share button from project page
  - [Warpcast Cast Intents](https://docs.farcaster.xyz/reference/warpcast/cast-composer-intents)
- Write an article
- Add issues to board
- Submit for whitelist approval
- Add WTF view explaining what is going on
- Clear image cache
- Fix Neynar verification
- Add Airstack tracking
- Animate success `.gif`
- Investigate `3737ms` response time
- Add ability to select wallet from mobile :shrug:
- Test and determine how we want to handle `if (!metaRes.data.records[0])` error
- Update `if !isActive` error to have separate errors for "Coming Soon" or "YEET Ended"
  - If "YEET Ended" show either Success or Failure view
- Optimize code
  - Reduce redundancy of styles
  - Possibly break into multiple files 

## Thoughts

- Kinda always need an active campaign to demonstrate the concept

## Ideas

- Bot that posts to a channel when people contribute or proposals are created

**Comment by skuhlmann** [comment]
Info for the error handling:

`Update if (!yeetData.data.yeeter) error`
- this is an error when we can't find the yeeter record in the subgraph so  the shaman doesn't exist. We can't pull any data on it and shouldn't let a tx move forward - could be someone messing with the shaman address in the url.

`Update if !isActive error`
- seems pretty self explanitory. the check here is looking if the yeet period has started or is over. so make this generic to the fact that we're not in the yeeter period. we could add more logic eventually to show that it's coming soon or over - but maybe not needed to ship?

 `Update if (!metaRes.data.records[0]) error`
 - this happens if the yeeter metadata hasn't been edited/added. without this we can't display the mission data. Maybe we just default the mission data in this case instead of blocking the yeet tx?

**Comment by skuhlmann** [comment]
What are you thinking here?

`Update: browserLocation: 'https://app.yeet.haus/',`

This is the redirect if someone visits the frame in a browser. Otherwise you'll see a white screen. I think that is a good spot to send them. it can't be dynamic at this level.

**Comment by earth2travis** [comment]
> What are you thinking here?
> 
> `Update: browserLocation: 'https://app.yeet.haus/',`
> 
> This is the redirect if someone visits the frame in a browser. Otherwise you'll see a white screen. I think that is a good spot to send them. it can't be dynamic at this level.

Good to know. That should be fine for now. Was thinking it would be `frames.yeet.haus` but `app` makes more sense

**Comment by earth2travis** [comment]
We fucking did it!

https://warpcast.com/earth2travis/0xc300792b

**Comment by earth2travis** [comment]
Did not do a good job of documenting the issues and fixes here. But this is where the conversation started on the [👼-dev](https://discord.com/channels/931307737365757973/1162082206529900674/1228402823012683898) channel on Discord
